### PR TITLE
[WIP] Add metrics into cluster-loader

### PR DESCRIPTION
**Pull request by hongkailiu**
Start from 3 type of SLOs: TestDurationSLO, ResourceStateSLO, and ExecutableSLO.

Their meaning is described in the corresponding passCheck() method.

We could specify the SLOs in cluster-loader config files. Here is an example:

```
slos:
  - name: slo1
    type: TestDurationSLO
    testDuration: 1m7s
  - name: slo2
    type: ResourceStateSLO
    resourceType: build
    number: 3
    operator: eq
    state: Complete
    selector:
      - app: web-server
  - name: slo3
    type: ExecutableSLO
    path: /root/myscript
    timeout: 1m7s
```

### CODE REVIEW

**Comment by mffiedler** [comment]
Maybe it's just me, but the SLO naming pattern seems odd.   Proposal

- Name the section something like "metrics" or "measurements" instead of "slos"
- Use type values closer to the English:  TestDuration, ResourceState, Executable

Not a big deal but might be more readable.

**Comment by hongkailiu** [comment]
@mffiedler: Renamed structs in src. Then updated version of config looks like this:

```
metrics:
  - name: m1
    type: TestDuration
    testDuration: 1m7s
  - name: m2
    type: ResourceState
    resourceType: build
    number: 3
    operator: eq
    state: Complete
    selector:
      - app: web-server
  - name: m3
    type: Executable
    path: /root/myscript
    timeout: 1m7s
```

**Comment by sjug** [comment]
I'm not sure I understand what's going on. Is there a document corresponding to this PR that I should read prior to asking questions here? I was thinking we were going to ouput some metrics at the end of the run for post-processing and import into Elasticsearch.

**Comment by hongkailiu** [comment]
I did this for [this card](https://trello.com/c/A29YkNqO/544-3toolsscale-310-cluster-loader-improved-logging).

And then started to ask you how to proceed via IRC:

```
(09:12:47 AM) hongkliu: sejug: can you specify one logging line that we need to convert to json? I will use that as my starting point
(09:13:08 AM) sejug: so right now there is the `testDuration` for example
(09:13:12 AM) sejug: we want to have that in json
(09:13:31 AM) hongkliu: sejug: checking ...
(09:14:05 AM) sejug: part of the task would be to define the SLO's of the various tests that we run
(09:14:13 AM) sejug: and then add those metrics into the end of run log
(09:14:27 AM) sejug: then define a json schema with that information
(09:14:32 AM) sejug: then finally just implement it
```

This is for the json output in logging for cluster-loader.

As a starting point, `TestDuration` which is one type of SLOs as json will be logged.
I defined the struct in `metrics.go`.

Another 2 SLOs/metrics are defined as well.

* `ResourceState`: we can check the expected status of pods/builds ... according to config file.
* `Executable`: more general case: we can run an executable script and output its output.

So in total for now, 3 types of metrics are defined for logging of cluster-loader and the corresponding json contents are represented by their structs.

**Comment by sjug** [comment]
Hey @hongkailiu,

This is good work, but not what I expected for the card or from the conversation. From what I've seen this PR is more around the user configuration input to define new metrics.

Lets shrink down the scope of the card as what we need to begin with is just an output schema for basic information that we're already collecting [like the test duration](https://github.com/openshift/origin/blob/master/test/extended/cluster/cl.go#L177-L179).

We need help to formalize the schema for the output end of the metrics that we get from the test execution. This way the stdout of the run can be parsed and we can get the metrics we need.

**Comment by hongkailiu** [comment]
/close

Will reopen when needed.

**Pull request closed without merging**
